# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-13 10:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_teacher_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseorg',
            name='tag',
            field=models.CharField(default='World Class', max_length=20, verbose_name='organization_tag'),
        ),
    ]
