# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-19 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180614_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverifyrecord',
            name='send_type',
            field=models.CharField(choices=[('register', 'New_User'), ('forget', 'Forget_Password')], max_length=10),
        ),
    ]
