# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-08 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20180619_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverifyrecord',
            name='send_type',
            field=models.CharField(choices=[('register', 'New User'), ('forget', 'Forget Password'), ('update', 'Update Email')], max_length=20),
        ),
    ]
