# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-08 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20180708_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverifyrecord',
            name='send_type',
            field=models.CharField(choices=[('register', 'New_User'), ('forget', 'Forget_Password'), ('update', 'Update_Email')], max_length=20),
        ),
    ]
