# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-13 16:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='lesson_name')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='add_time')),
            ],
            options={
                'verbose_name': 'course_chapter',
                'verbose_name_plural': 'course_chapter',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='course_name')),
                ('desc', models.CharField(max_length=300, verbose_name='course_desc')),
                ('detail', models.TextField(verbose_name='course_detail')),
                ('degree', models.CharField(choices=[('entry', 'entry_level'), ('intermediate', 'mid_level'), ('advanced', 'advanced_level')], max_length=2)),
                ('learn_time', models.IntegerField(default=0, verbose_name='learning_time')),
                ('students_num', models.IntegerField(default=0, verbose_name='students_num')),
                ('fav_num', models.IntegerField(default=0, verbose_name='fav_num')),
                ('image', models.ImageField(upload_to='courses/%Y/%m', verbose_name='cover_image')),
                ('click_num', models.IntegerField(default=0, verbose_name='click_num')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='add_time')),
            ],
            options={
                'verbose_name': 'course',
                'verbose_name_plural': 'course',
            },
        ),
        migrations.CreateModel(
            name='CourseResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('download', models.FileField(upload_to='course/resource/%Y/%m', verbose_name='resource_file')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='add_time')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Course', verbose_name='course')),
            ],
            options={
                'verbose_name': 'course_resource',
                'verbose_name_plural': 'course_resource',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='video_name')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='add_time')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Chapter', verbose_name='chapter_video')),
            ],
            options={
                'verbose_name': 'course_video',
                'verbose_name_plural': 'course_video',
            },
        ),
        migrations.AddField(
            model_name='chapter',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Course', verbose_name='chapter'),
        ),
    ]
