# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-03 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_duration',
            field=models.IntegerField(default=0, verbose_name='video_duration'),
        ),
    ]
