# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-03 17:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_teacher_image'),
        ('course', '0008_video_video_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.Teacher', verbose_name='instructor'),
        ),
    ]
