# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-12 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_auto_20180703_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_banner',
            field=models.BooleanField(default=False, verbose_name='is_banner'),
        ),
    ]
