# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-18 21:26
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_course_is_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerCourse',
            fields=[
            ],
            options={
                'verbose_name': 'Banner Course',
                'verbose_name_plural': 'Banner Course',
                'proxy': True,
                'indexes': [],
            },
            bases=('course.course',),
        ),
        migrations.AlterField(
            model_name='course',
            name='degree',
            field=models.CharField(choices=[('entry', 'Elementary'), ('intermediate', 'Junior'), ('advanced', 'Advanced')], max_length=20, verbose_name='course_degree'),
        ),
        migrations.AlterField(
            model_name='course',
            name='detail',
            field=DjangoUeditor.models.UEditorField(default='', verbose_name='course_detail'),
        ),
    ]
